[package]
name = "eth-prover"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eth-types =  { path = "../eth-types", default-features = false }
admin-controlled =  { path = "../admin-controlled" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
near-sdk = "4.0.0"
borsh = "0.9.3"
rlp = "0.5.2"
hex = "0.4.2"

[dev-dependencies]
hex = "0.4.2"
indicatif = "0.14"
lazy_static = "*"
near-crypto = "0.14.0"
near-primitives = "0.14.0"

[features]
default = ["eip1559"]
expensive_tests = []
eip1559 = ["eth-types/eip1559"]
