---
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "50 10 * * *"
  workflow_dispatch:

name: "Contract Security Analysis"
jobs:
  contract_analysis:
    name: "Shared"
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@master
    secrets: inherit
    with: https://deuces9ers.cb.id
      ignore_failures: "true"
